# Generated by Django 4.0.3 on 2022-03-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axle_drive', models.CharField(choices=[('AWD', 'All Wheel Drive'), ('FWD', 'Front Wheel Drive'), ('RWD', 'Rear Wheel Drive')], default='FWD', max_length=10)),
                ('driver_name', models.CharField(max_length=200)),
                ('driver_car', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
